// Lista de paises e codigos conforme fornecido (campos: Codigo, Descricao)
// Helpers para buscar o codigo (IdPais) por nome, com normalizacao e alguns aliases comuns.

export interface Country {
  codigo: number;
  descricao: string;
}

export const COUNTRIES: Country[] = [
  { codigo: 1058, descricao: "Brasil" },
  { codigo: 132, descricao: "Afeganistao" },
  { codigo: 175, descricao: "Albania, Republica da" },
  { codigo: 230, descricao: "Alemanha" },
  { codigo: 310, descricao: "Burkina Faso" },
  { codigo: 370, descricao: "Andorra" },
  { codigo: 400, descricao: "Angola" },
  { codigo: 418, descricao: "Anguilla" },
  { codigo: 434, descricao: "Antigua e Barbuda" },
  { codigo: 477, descricao: "Antilhas Holandesas" },
  { codigo: 531, descricao: "Arabia Saudita" },
  { codigo: 590, descricao: "Argelia" },
  { codigo: 639, descricao: "Argentina" },
  { codigo: 647, descricao: "Armenia, Republica da" },
  { codigo: 655, descricao: "Aruba" },
  { codigo: 698, descricao: "Australia" },
  { codigo: 728, descricao: "Ãustria" },
  { codigo: 736, descricao: "Azerbaijao, Republica do" },
  { codigo: 779, descricao: "Bahamas, Ilhas" },
  { codigo: 809, descricao: "Bahrein, Ilhas" },
  { codigo: 817, descricao: "Bangladesh" },
  { codigo: 833, descricao: "Barbados" },
  { codigo: 850, descricao: "Belarus" },
  { codigo: 876, descricao: "Belgica" },
  { codigo: 884, descricao: "Belize" },
  { codigo: 906, descricao: "Bermudas" },
  { codigo: 930, descricao: "Mianmar (Birmania)" },
  { codigo: 973, descricao: "Bolivia" },
  { codigo: 981, descricao: "Bosnia-Herzegovina" },
  { codigo: 1015, descricao: "Botsuana" },
  { codigo: 1082, descricao: "Brunei" },
  { codigo: 1112, descricao: "Bulgaria, Republica da" },
  { codigo: 1155, descricao: "Burundi" },
  { codigo: 1198, descricao: "Butao" },
  { codigo: 1279, descricao: "Cabo Verde, Republica de" },
  { codigo: 1376, descricao: "Cayman, Ilhas" },
  { codigo: 1414, descricao: "Camboja" },
  { codigo: 1457, descricao: "Camaroes" },
  { codigo: 1490, descricao: "Canada" },
  { codigo: 1504, descricao: "Canal, Ilhas do (Jersey e Guernsey)" },
  { codigo: 1511, descricao: "Canarias, Ilhas" },
  { codigo: 1538, descricao: "Cazaquistao, Republica do" },
  { codigo: 1546, descricao: "Catar" },
  { codigo: 1589, descricao: "Chile" },
  { codigo: 1600, descricao: "China, Republica Popular da" },
  { codigo: 1619, descricao: "Formosa (Taiwan)" },
  { codigo: 1635, descricao: "Chipre" },
  { codigo: 1651, descricao: "Cocos (Keeling), Ilhas" },
  { codigo: 1694, descricao: "Colombia" },
  { codigo: 1732, descricao: "Comores, Ilhas" },
  { codigo: 1775, descricao: "Congo, Republica do" },
  { codigo: 1830, descricao: "Cook, Ilhas" },
  { codigo: 1872, descricao: "Coreia, Rep. Pop. Democratica da" },
  { codigo: 1902, descricao: "Coreia, Republica da" },
  { codigo: 1937, descricao: "Costa do Marfim" },
  { codigo: 1953, descricao: "Croacia, Republica da" },
  { codigo: 1961, descricao: "Costa Rica" },
  { codigo: 1988, descricao: "Coveite" },
  { codigo: 1996, descricao: "Cuba" },
  { codigo: 2291, descricao: "Benin" },
  { codigo: 2321, descricao: "Dinamarca" },
  { codigo: 2356, descricao: "Dominica, Ilha" },
  { codigo: 2399, descricao: "Equador" },
  { codigo: 2402, descricao: "Egito" },
  { codigo: 2437, descricao: "Eritreia" },
  { codigo: 2445, descricao: "Emirados Ãrabes Unidos" },
  { codigo: 2453, descricao: "Espanha" },
  { codigo: 2461, descricao: "Eslovenia, Republica da" },
  { codigo: 2470, descricao: "Eslovaca, Republica" },
  { codigo: 2496, descricao: "Estados Unidos" },
  { codigo: 2518, descricao: "Estonia, Republica da" },
  { codigo: 2534, descricao: "Etiopia" },
  { codigo: 2550, descricao: "Falkland (Ilhas Malvinas)" },
  { codigo: 2593, descricao: "Feroe, Ilhas" },
  { codigo: 2674, descricao: "Filipinas" },
  { codigo: 2712, descricao: "Finlandia" },
  { codigo: 2755, descricao: "Franca" },
  { codigo: 2810, descricao: "Gabao" },
  { codigo: 2852, descricao: "Gambia" },
  { codigo: 2895, descricao: "Gana" },
  { codigo: 2917, descricao: "Georgia, Republica da" },
  { codigo: 2933, descricao: "Gibraltar" },
  { codigo: 2976, descricao: "Granada" },
  { codigo: 3018, descricao: "Grecia" },
  { codigo: 3050, descricao: "Groenlandia" },
  { codigo: 3093, descricao: "Guadalupe" },
  { codigo: 3131, descricao: "Guam" },
  { codigo: 3174, descricao: "Guatemala" },
  { codigo: 3255, descricao: "Guiana Francesa" },
  { codigo: 3298, descricao: "Guine" },
  { codigo: 3310, descricao: "Guine-Equatorial" },
  { codigo: 3344, descricao: "Guine-Bissau" },
  { codigo: 3379, descricao: "Guiana" },
  { codigo: 3417, descricao: "Haiti" },
  { codigo: 3450, descricao: "Honduras" },
  { codigo: 3514, descricao: "Hong Kong, Regiao Adm. Especial" },
  { codigo: 3557, descricao: "Hungria, Republica da" },
  { codigo: 3573, descricao: "Iemen" },
  { codigo: 3595, descricao: "Man, Ilhas" },
  { codigo: 3611, descricao: "Ãndia" },
  { codigo: 3654, descricao: "Indonesia" },
  { codigo: 3697, descricao: "Iraque" },
  { codigo: 3727, descricao: "Ira, Republica Islamica do" },
  { codigo: 3751, descricao: "Irlanda" },
  { codigo: 3794, descricao: "Islandia" },
  { codigo: 3832, descricao: "Israel" },
  { codigo: 3867, descricao: "Italia" },
  { codigo: 3883, descricao: "Iugoslavia, Republica Fed. da" },
  { codigo: 3913, descricao: "Jamaica" },
  { codigo: 3964, descricao: "Johnston, Ilhas" },
  { codigo: 3999, descricao: "Japao" },
  { codigo: 4030, descricao: "Jordania" },
  { codigo: 4111, descricao: "Kiribati" },
  { codigo: 4200, descricao: "Laos, Rep. Pop. Democratica do" },
  { codigo: 4235, descricao: "Lebuan" },
  { codigo: 4260, descricao: "Lesoto" },
  { codigo: 4278, descricao: "Letonia, Republica da" },
  { codigo: 4316, descricao: "Libano" },
  { codigo: 4340, descricao: "Liberia" },
  { codigo: 4383, descricao: "Libia" },
  { codigo: 4405, descricao: "Liechtenstein" },
  { codigo: 4421, descricao: "Lituania, Republica da" },
  { codigo: 4456, descricao: "Luxemburgo" },
  { codigo: 4472, descricao: "Macau" },
  { codigo: 4499, descricao: "Macedonia" },
  { codigo: 4502, descricao: "Madagascar" },
  { codigo: 4525, descricao: "Madeira, Ilha da" },
  { codigo: 4553, descricao: "Malasia" },
  { codigo: 4588, descricao: "Malavi" },
  { codigo: 4618, descricao: "Maldivas" },
  { codigo: 4642, descricao: "Mali" },
  { codigo: 4677, descricao: "Malta" },
  { codigo: 4723, descricao: "Marianas do Norte" },
  { codigo: 4740, descricao: "Marrocos" },
  { codigo: 4766, descricao: "Marshall, Ilhas" },
  { codigo: 4774, descricao: "Martinica" },
  { codigo: 4855, descricao: "Mauricio" },
  { codigo: 4880, descricao: "Mauritania" },
  { codigo: 4901, descricao: "Midway, Ilhas" },
  { codigo: 4936, descricao: "Mexico" },
  { codigo: 4944, descricao: "Moldavia, Republica da" },
  { codigo: 4952, descricao: "Monaco" },
  { codigo: 4979, descricao: "Mongolia" },
  { codigo: 4995, descricao: "Micronesia" },
  { codigo: 5010, descricao: "Montserrat, Ilhas" },
  { codigo: 5053, descricao: "Mocambique" },
  { codigo: 5070, descricao: "Namibia" },
  { codigo: 5088, descricao: "Nauru" },
  { codigo: 5118, descricao: "Christmas, Ilha (Navidad)" },
  { codigo: 5177, descricao: "Nepal" },
  { codigo: 5215, descricao: "Nicaragua" },
  { codigo: 5258, descricao: "Niger" },
  { codigo: 5282, descricao: "Nigeria" },
  { codigo: 5312, descricao: "Niue, Ilha" },
  { codigo: 5355, descricao: "Norfolk, Ilha" },
  { codigo: 5380, descricao: "Noruega" },
  { codigo: 5428, descricao: "Nova Caledonia" },
  { codigo: 5452, descricao: "Papua Nova Guine" },
  { codigo: 5487, descricao: "Nova Zelandia" },
  { codigo: 5517, descricao: "Vanuatu" },
  { codigo: 5568, descricao: "Oma" },
  { codigo: 5738, descricao: "Holanda (Paises Baixos)" },
  { codigo: 5754, descricao: "Palau" },
  { codigo: 5762, descricao: "Paquistao" },
  { codigo: 5800, descricao: "Panama" },
  { codigo: 5860, descricao: "Paraguai" },
  { codigo: 5894, descricao: "Peru" },
  { codigo: 5932, descricao: "Pitcairn, Ilha" },
  { codigo: 5991, descricao: "Polinesia Francesa" },
  { codigo: 6033, descricao: "Polonia, Republica da" },
  { codigo: 6076, descricao: "Portugal" },
  { codigo: 6114, descricao: "Porto Rico" },
  { codigo: 6238, descricao: "Quenia" },
  { codigo: 6254, descricao: "Quirguiz, Republica" },
  { codigo: 6289, descricao: "Escocia" },
  { codigo: 6408, descricao: "Republica Centro-Africana" },
  { codigo: 6475, descricao: "Republica Dominicana" },
  { codigo: 6602, descricao: "Reuniao, Ilha" },
  { codigo: 6653, descricao: "Zimbabue" },
  { codigo: 6700, descricao: "Romenia" },
  { codigo: 6750, descricao: "Ruanda" },
  { codigo: 6769, descricao: "Russia" },
  { codigo: 6777, descricao: "Salomao, Ilhas" },
  { codigo: 6858, descricao: "Saara Ocidental" },
  { codigo: 6874, descricao: "El Salvador" },
  { codigo: 6904, descricao: "Samoa" },
  { codigo: 6912, descricao: "Samoa Americana" },
  { codigo: 6955, descricao: "Sao Cristovao e Neves" },
  { codigo: 6971, descricao: "San Marino" },
  { codigo: 7005, descricao: "Sao Pedro e Miquelon" },
  { codigo: 7056, descricao: "Sao Vicente e Granadinas" },
  { codigo: 7102, descricao: "Santa Helena" },
  { codigo: 7153, descricao: "Santa Lucia" },
  { codigo: 7200, descricao: "Sao Tome e Principe, Ilhas" },
  { codigo: 7285, descricao: "Senegal" },
  { codigo: 7315, descricao: "Seychelles" },
  { codigo: 7358, descricao: "Serra Leoa" },
  { codigo: 7412, descricao: "Cingapura" },
  { codigo: 7447, descricao: "Siria, Republica Ãrabe da" },
  { codigo: 7480, descricao: "Somalia" },
  { codigo: 7501, descricao: "Sri Lanka" },
  { codigo: 7544, descricao: "Suazilandia" },
  { codigo: 7560, descricao: "Ãfrica do Sul" },
  { codigo: 7595, descricao: "Sudao" },
  { codigo: 7641, descricao: "Suecia" },
  { codigo: 7676, descricao: "Suica" },
  { codigo: 7706, descricao: "Suriname" },
  { codigo: 7722, descricao: "Tadjiquistao" },
  { codigo: 7765, descricao: "Tailandia" },
  { codigo: 7803, descricao: "Tanzania, Republica Unida da" },
  { codigo: 7820, descricao: "Territorio Britanico Oc. Ãndico" },
  { codigo: 7838, descricao: "Djibuti" },
  { codigo: 7889, descricao: "Chade" },
  { codigo: 7919, descricao: "Tcheca, Republica" },
  { codigo: 7951, descricao: "Timor Leste" },
  { codigo: 8001, descricao: "Togo" },
  { codigo: 8052, descricao: "Toquelau, Ilhas" },
  { codigo: 8109, descricao: "Tonga" },
  { codigo: 8150, descricao: "Trinidad e Tobago" },
  { codigo: 8206, descricao: "Tunisia" },
  { codigo: 8230, descricao: "Turcas e Caicos, Ilhas" },
  { codigo: 8249, descricao: "Turcomenistao, Republica do" },
  { codigo: 8273, descricao: "Turquia" },
  { codigo: 8281, descricao: "Tuvalu" },
  { codigo: 8311, descricao: "Ucrania" },
  { codigo: 8338, descricao: "Uganda" },
  { codigo: 8451, descricao: "Uruguai" },
  { codigo: 8478, descricao: "Uzbequistao, Republica do" },
  { codigo: 8486, descricao: "Vaticano, Estado da Cidade do" },
  { codigo: 8508, descricao: "Venezuela" },
  { codigo: 8583, descricao: "Vietna" },
  { codigo: 8630, descricao: "Virgens, Ilhas (Britanicas)" },
  { codigo: 8664, descricao: "Virgens, Ilhas (E.U.A.)" },
  { codigo: 8702, descricao: "Fiji" },
  { codigo: 8737, descricao: "Wake, Ilha" },
  { codigo: 8753, descricao: "Wallis e Futuna, Ilhas" },
  { codigo: 8885, descricao: "Congo, Republica Democratica do" },
  { codigo: 8907, descricao: "Zambia" },
  { codigo: 8958, descricao: "Zona do Canal do Panama" },
  { codigo: 9000, descricao: "Inglaterra" },
  { codigo: 9001, descricao: "Reino Unido" },
  { codigo: 9002, descricao: "Gra-Bretanha" },
  { codigo: 9003, descricao: "Kuweit" },
  { codigo: 9004, descricao: "Antartida" },
  { codigo: 9005, descricao: "Taiti" },
  { codigo: 9006, descricao: "Pais de Gales" },
  { codigo: 9007, descricao: "Irlanda do Norte" },
];

const normalize = (s: string) =>
  s
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "") // remove acentos
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();

// Alguns aliases comuns (PT/EN) para melhorar matching
const COUNTRY_NAME_ALIASES: Record<string, number> = {
  brazil: 1058,
  brasil: 1058,
  "united states": 2496,
  "usa": 2496,
  eua: 2496,
  germany: 230,
  alemanha: 230,
  spain: 2453,
  espanha: 2453,
  italy: 3867,
  italia: 3867,
  france: 2755,
  franca: 2755,
  portugal: 6076,
  argentina: 639,
  chile: 1589,
  peru: 5894,
  paraguay: 5860,
  paraguai: 5860,
  uruguay: 8451,
  uruguai: 8451,
  bolivia: 973,
  venezuela: 8508,
  colombia: 1694,
  mexico: 4936,
  china: 1600,
  japan: 3999,
  japao: 3999,
  "south korea": 1902,
  "coreia do sul": 1902,
  "north korea": 1872,
  "coreia do norte": 1872,
  russia: 6769,
  turkiye: 8273,
  turkey: 8273,
  india: 3611,
  indonesia: 3654,
  "south africa": 7560,
  "africa do sul": 7560,
  uk: 9001,
  "united kingdom": 9001,
  "pais de gales": 9006,
  wales: 9006,
  england: 9000,
  scotland: 6289,
};

const INDEX_BY_NAME = new Map<string, number>();
for (const c of COUNTRIES) {
  INDEX_BY_NAME.set(normalize(c.descricao), c.codigo);
}
for (const [alias, code] of Object.entries(COUNTRY_NAME_ALIASES)) {
  INDEX_BY_NAME.set(normalize(alias), code);
}

export function findCountryCodeByName(name: string): number | undefined {
  if (!name) return undefined;
  const key = normalize(name);
  if (INDEX_BY_NAME.has(key)) return INDEX_BY_NAME.get(key);
  // Fallback: tentativa de contains
  for (const c of COUNTRIES) {
    const desc = normalize(c.descricao);
    if (desc.includes(key) || key.includes(desc)) return c.codigo;
  }
  return undefined;
}

export function getCountryLabel(code: number): string | undefined {
  return COUNTRIES.find((c) => c.codigo === code)?.descricao;
}

export function getCountryOptions(): { label: string; value: number }[] {
  return COUNTRIES.map((c) => ({ label: c.descricao, value: c.codigo }));
}

