// Lista de países e códigos conforme fornecido (campos: Código, Descrição)
// Helpers para buscar o código (IdPais) por nome, com normalização e alguns aliases comuns.

export interface Country {
  codigo: number;
  descricao: string;
}

export const COUNTRIES: Country[] = [
  { codigo: 1058, descricao: "Brasil" },
  { codigo: 132, descricao: "Afeganistão" },
  { codigo: 175, descricao: "Albânia, República da" },
  { codigo: 230, descricao: "Alemanha" },
  { codigo: 310, descricao: "Burkina Faso" },
  { codigo: 370, descricao: "Andorra" },
  { codigo: 400, descricao: "Angola" },
  { codigo: 418, descricao: "Anguilla" },
  { codigo: 434, descricao: "Antigua e Barbuda" },
  { codigo: 477, descricao: "Antilhas Holandesas" },
  { codigo: 531, descricao: "Arábia Saudita" },
  { codigo: 590, descricao: "Argélia" },
  { codigo: 639, descricao: "Argentina" },
  { codigo: 647, descricao: "Armênia, República da" },
  { codigo: 655, descricao: "Aruba" },
  { codigo: 698, descricao: "Austrália" },
  { codigo: 728, descricao: "Áustria" },
  { codigo: 736, descricao: "Azerbaijão, República do" },
  { codigo: 779, descricao: "Bahamas, Ilhas" },
  { codigo: 809, descricao: "Bahrein, Ilhas" },
  { codigo: 817, descricao: "Bangladesh" },
  { codigo: 833, descricao: "Barbados" },
  { codigo: 850, descricao: "Belarus" },
  { codigo: 876, descricao: "Bélgica" },
  { codigo: 884, descricao: "Belize" },
  { codigo: 906, descricao: "Bermudas" },
  { codigo: 930, descricao: "Mianmar (Birmânia)" },
  { codigo: 973, descricao: "Bolívia" },
  { codigo: 981, descricao: "Bósnia-Herzegovina" },
  { codigo: 1015, descricao: "Botsuana" },
  { codigo: 1082, descricao: "Brunei" },
  { codigo: 1112, descricao: "Bulgária, República da" },
  { codigo: 1155, descricao: "Burundi" },
  { codigo: 1198, descricao: "Butão" },
  { codigo: 1279, descricao: "Cabo Verde, República de" },
  { codigo: 1376, descricao: "Cayman, Ilhas" },
  { codigo: 1414, descricao: "Camboja" },
  { codigo: 1457, descricao: "Camarões" },
  { codigo: 1490, descricao: "Canadá" },
  { codigo: 1504, descricao: "Canal, Ilhas do (Jersey e Guernsey)" },
  { codigo: 1511, descricao: "Canárias, Ilhas" },
  { codigo: 1538, descricao: "Cazaquistão, República do" },
  { codigo: 1546, descricao: "Catar" },
  { codigo: 1589, descricao: "Chile" },
  { codigo: 1600, descricao: "China, República Popular da" },
  { codigo: 1619, descricao: "Formosa (Taiwan)" },
  { codigo: 1635, descricao: "Chipre" },
  { codigo: 1651, descricao: "Cocos (Keeling), Ilhas" },
  { codigo: 1694, descricao: "Colômbia" },
  { codigo: 1732, descricao: "Comores, Ilhas" },
  { codigo: 1775, descricao: "Congo, República do" },
  { codigo: 1830, descricao: "Cook, Ilhas" },
  { codigo: 1872, descricao: "Coréia, Rep. Pop. Democrática da" },
  { codigo: 1902, descricao: "Coréia, República da" },
  { codigo: 1937, descricao: "Costa do Marfim" },
  { codigo: 1953, descricao: "Croácia, República da" },
  { codigo: 1961, descricao: "Costa Rica" },
  { codigo: 1988, descricao: "Coveite" },
  { codigo: 1996, descricao: "Cuba" },
  { codigo: 2291, descricao: "Benin" },
  { codigo: 2321, descricao: "Dinamarca" },
  { codigo: 2356, descricao: "Dominica, Ilha" },
  { codigo: 2399, descricao: "Equador" },
  { codigo: 2402, descricao: "Egito" },
  { codigo: 2437, descricao: "Eritréia" },
  { codigo: 2445, descricao: "Emirados Árabes Unidos" },
  { codigo: 2453, descricao: "Espanha" },
  { codigo: 2461, descricao: "Eslovênia, República da" },
  { codigo: 2470, descricao: "Eslovaca, República" },
  { codigo: 2496, descricao: "Estados Unidos" },
  { codigo: 2518, descricao: "Estônia, República da" },
  { codigo: 2534, descricao: "Etiópia" },
  { codigo: 2550, descricao: "Falkland (Ilhas Malvinas)" },
  { codigo: 2593, descricao: "Feroe, Ilhas" },
  { codigo: 2674, descricao: "Filipinas" },
  { codigo: 2712, descricao: "Finlândia" },
  { codigo: 2755, descricao: "França" },
  { codigo: 2810, descricao: "Gabão" },
  { codigo: 2852, descricao: "Gâmbia" },
  { codigo: 2895, descricao: "Gana" },
  { codigo: 2917, descricao: "Geórgia, República da" },
  { codigo: 2933, descricao: "Gibraltar" },
  { codigo: 2976, descricao: "Granada" },
  { codigo: 3018, descricao: "Grécia" },
  { codigo: 3050, descricao: "Groenlândia" },
  { codigo: 3093, descricao: "Guadalupe" },
  { codigo: 3131, descricao: "Guam" },
  { codigo: 3174, descricao: "Guatemala" },
  { codigo: 3255, descricao: "Guiana Francesa" },
  { codigo: 3298, descricao: "Guiné" },
  { codigo: 3310, descricao: "Guiné-Equatorial" },
  { codigo: 3344, descricao: "Guiné-Bissau" },
  { codigo: 3379, descricao: "Guiana" },
  { codigo: 3417, descricao: "Haiti" },
  { codigo: 3450, descricao: "Honduras" },
  { codigo: 3514, descricao: "Hong Kong, Região Adm. Especial" },
  { codigo: 3557, descricao: "Hungria, República da" },
  { codigo: 3573, descricao: "Iêmen" },
  { codigo: 3595, descricao: "Man, Ilhas" },
  { codigo: 3611, descricao: "Índia" },
  { codigo: 3654, descricao: "Indonésia" },
  { codigo: 3697, descricao: "Iraque" },
  { codigo: 3727, descricao: "Irã, República Islâmica do" },
  { codigo: 3751, descricao: "Irlanda" },
  { codigo: 3794, descricao: "Islândia" },
  { codigo: 3832, descricao: "Israel" },
  { codigo: 3867, descricao: "Itália" },
  { codigo: 3883, descricao: "Iugoslávia, República Fed. da" },
  { codigo: 3913, descricao: "Jamaica" },
  { codigo: 3964, descricao: "Johnston, Ilhas" },
  { codigo: 3999, descricao: "Japão" },
  { codigo: 4030, descricao: "Jordânia" },
  { codigo: 4111, descricao: "Kiribati" },
  { codigo: 4200, descricao: "Laos, Rep. Pop. Democrática do" },
  { codigo: 4235, descricao: "Lebuan" },
  { codigo: 4260, descricao: "Lesoto" },
  { codigo: 4278, descricao: "Letônia, República da" },
  { codigo: 4316, descricao: "Líbano" },
  { codigo: 4340, descricao: "Libéria" },
  { codigo: 4383, descricao: "Líbia" },
  { codigo: 4405, descricao: "Liechtenstein" },
  { codigo: 4421, descricao: "Lituânia, República da" },
  { codigo: 4456, descricao: "Luxemburgo" },
  { codigo: 4472, descricao: "Macau" },
  { codigo: 4499, descricao: "Macedônia" },
  { codigo: 4502, descricao: "Madagascar" },
  { codigo: 4525, descricao: "Madeira, Ilha da" },
  { codigo: 4553, descricao: "Malásia" },
  { codigo: 4588, descricao: "Malavi" },
  { codigo: 4618, descricao: "Maldivas" },
  { codigo: 4642, descricao: "Máli" },
  { codigo: 4677, descricao: "Malta" },
  { codigo: 4723, descricao: "Marianas do Norte" },
  { codigo: 4740, descricao: "Marrocos" },
  { codigo: 4766, descricao: "Marshall, Ilhas" },
  { codigo: 4774, descricao: "Martinica" },
  { codigo: 4855, descricao: "Maurício" },
  { codigo: 4880, descricao: "Mauritânia" },
  { codigo: 4901, descricao: "Midway, Ilhas" },
  { codigo: 4936, descricao: "México" },
  { codigo: 4944, descricao: "Moldávia, República da" },
  { codigo: 4952, descricao: "Mônaco" },
  { codigo: 4979, descricao: "Mongólia" },
  { codigo: 4995, descricao: "Micronésia" },
  { codigo: 5010, descricao: "Montserrat, Ilhas" },
  { codigo: 5053, descricao: "Moçambique" },
  { codigo: 5070, descricao: "Namíbia" },
  { codigo: 5088, descricao: "Nauru" },
  { codigo: 5118, descricao: "Christmas, Ilha (Navidad)" },
  { codigo: 5177, descricao: "Nepal" },
  { codigo: 5215, descricao: "Nicarágua" },
  { codigo: 5258, descricao: "Niger" },
  { codigo: 5282, descricao: "Nigéria" },
  { codigo: 5312, descricao: "Niue, Ilha" },
  { codigo: 5355, descricao: "Norfolk, Ilha" },
  { codigo: 5380, descricao: "Noruega" },
  { codigo: 5428, descricao: "Nova Caledônia" },
  { codigo: 5452, descricao: "Papua Nova Guiné" },
  { codigo: 5487, descricao: "Nova Zelândia" },
  { codigo: 5517, descricao: "Vanuatu" },
  { codigo: 5568, descricao: "Omã" },
  { codigo: 5738, descricao: "Holanda (Países Baixos)" },
  { codigo: 5754, descricao: "Palau" },
  { codigo: 5762, descricao: "Paquistão" },
  { codigo: 5800, descricao: "Panamá" },
  { codigo: 5860, descricao: "Paraguai" },
  { codigo: 5894, descricao: "Peru" },
  { codigo: 5932, descricao: "Pitcairn, Ilha" },
  { codigo: 5991, descricao: "Polinésia Francesa" },
  { codigo: 6033, descricao: "Polônia, República da" },
  { codigo: 6076, descricao: "Portugal" },
  { codigo: 6114, descricao: "Porto Rico" },
  { codigo: 6238, descricao: "Quênia" },
  { codigo: 6254, descricao: "Quirguiz, República" },
  { codigo: 6289, descricao: "Escócia" },
  { codigo: 6408, descricao: "República Centro-Africana" },
  { codigo: 6475, descricao: "República Dominicana" },
  { codigo: 6602, descricao: "Reunião, Ilha" },
  { codigo: 6653, descricao: "Zimbábue" },
  { codigo: 6700, descricao: "Romênia" },
  { codigo: 6750, descricao: "Ruanda" },
  { codigo: 6769, descricao: "Rússia" },
  { codigo: 6777, descricao: "Salomão, Ilhas" },
  { codigo: 6858, descricao: "Saara Ocidental" },
  { codigo: 6874, descricao: "El Salvador" },
  { codigo: 6904, descricao: "Samoa" },
  { codigo: 6912, descricao: "Samoa Americana" },
  { codigo: 6955, descricao: "São Cristóvão e Neves" },
  { codigo: 6971, descricao: "San Marino" },
  { codigo: 7005, descricao: "São Pedro e Miquelon" },
  { codigo: 7056, descricao: "São Vicente e Granadinas" },
  { codigo: 7102, descricao: "Santa Helena" },
  { codigo: 7153, descricao: "Santa Lúcia" },
  { codigo: 7200, descricao: "São Tomé e Príncipe, Ilhas" },
  { codigo: 7285, descricao: "Senegal" },
  { codigo: 7315, descricao: "Seychelles" },
  { codigo: 7358, descricao: "Serra Leoa" },
  { codigo: 7412, descricao: "Cingapura" },
  { codigo: 7447, descricao: "Síria, República Árabe da" },
  { codigo: 7480, descricao: "Somália" },
  { codigo: 7501, descricao: "Sri Lanka" },
  { codigo: 7544, descricao: "Suazilândia" },
  { codigo: 7560, descricao: "África do Sul" },
  { codigo: 7595, descricao: "Sudão" },
  { codigo: 7641, descricao: "Suécia" },
  { codigo: 7676, descricao: "Suíça" },
  { codigo: 7706, descricao: "Suriname" },
  { codigo: 7722, descricao: "Tadjiquistão" },
  { codigo: 7765, descricao: "Tailândia" },
  { codigo: 7803, descricao: "Tanzânia, República Unida da" },
  { codigo: 7820, descricao: "Território Britânico Oc. Índico" },
  { codigo: 7838, descricao: "Djibuti" },
  { codigo: 7889, descricao: "Chade" },
  { codigo: 7919, descricao: "Tcheca, República" },
  { codigo: 7951, descricao: "Timor Leste" },
  { codigo: 8001, descricao: "Togo" },
  { codigo: 8052, descricao: "Toquelau, Ilhas" },
  { codigo: 8109, descricao: "Tonga" },
  { codigo: 8150, descricao: "Trinidad e Tobago" },
  { codigo: 8206, descricao: "Tunísia" },
  { codigo: 8230, descricao: "Turcas e Caicos, Ilhas" },
  { codigo: 8249, descricao: "Turcomenistão, República do" },
  { codigo: 8273, descricao: "Turquia" },
  { codigo: 8281, descricao: "Tuvalu" },
  { codigo: 8311, descricao: "Ucrânia" },
  { codigo: 8338, descricao: "Uganda" },
  { codigo: 8451, descricao: "Uruguai" },
  { codigo: 8478, descricao: "Uzbequistão, República do" },
  { codigo: 8486, descricao: "Vaticano, Estado da Cidade do" },
  { codigo: 8508, descricao: "Venezuela" },
  { codigo: 8583, descricao: "Vietnã" },
  { codigo: 8630, descricao: "Virgens, Ilhas (Britânicas)" },
  { codigo: 8664, descricao: "Virgens, Ilhas (E.U.A.)" },
  { codigo: 8702, descricao: "Fiji" },
  { codigo: 8737, descricao: "Wake, Ilha" },
  { codigo: 8753, descricao: "Wallis e Futuna, Ilhas" },
  { codigo: 8885, descricao: "Congo, República Democrática do" },
  { codigo: 8907, descricao: "Zâmbia" },
  { codigo: 8958, descricao: "Zona do Canal do Panamá" },
  { codigo: 9000, descricao: "Inglaterra" },
  { codigo: 9001, descricao: "Reino Unido" },
  { codigo: 9002, descricao: "Grã-Bretanha" },
  { codigo: 9003, descricao: "Kuweit" },
  { codigo: 9004, descricao: "Antártida" },
  { codigo: 9005, descricao: "Taiti" },
  { codigo: 9006, descricao: "País de Gales" },
  { codigo: 9007, descricao: "Irlanda do Norte" },
];

const normalize = (s: string) =>
  s
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "") // remove acentos
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();

// Alguns aliases comuns (PT/EN) para melhorar matching
const COUNTRY_NAME_ALIASES: Record<string, number> = {
  brazil: 1058,
  brasil: 1058,
  "united states": 2496,
  "usa": 2496,
  eua: 2496,
  germany: 230,
  alemanha: 230,
  spain: 2453,
  espanha: 2453,
  italy: 3867,
  italia: 3867,
  france: 2755,
  franca: 2755,
  portugal: 6076,
  argentina: 639,
  chile: 1589,
  peru: 5894,
  paraguay: 5860,
  paraguai: 5860,
  uruguay: 8451,
  uruguai: 8451,
  bolivia: 973,
  venezuela: 8508,
  colombia: 1694,
  mexico: 4936,
  china: 1600,
  japan: 3999,
  japao: 3999,
  "south korea": 1902,
  "coreia do sul": 1902,
  "north korea": 1872,
  "coreia do norte": 1872,
  russia: 6769,
  turkiye: 8273,
  turkey: 8273,
  india: 3611,
  indonesia: 3654,
  "south africa": 7560,
  "africa do sul": 7560,
  uk: 9001,
  "united kingdom": 9001,
  "pais de gales": 9006,
  wales: 9006,
  england: 9000,
  scotland: 6289,
};

const INDEX_BY_NAME = new Map<string, number>();
for (const c of COUNTRIES) {
  INDEX_BY_NAME.set(normalize(c.descricao), c.codigo);
}
for (const [alias, code] of Object.entries(COUNTRY_NAME_ALIASES)) {
  INDEX_BY_NAME.set(normalize(alias), code);
}

export function findCountryCodeByName(name: string): number | undefined {
  if (!name) return undefined;
  const key = normalize(name);
  if (INDEX_BY_NAME.has(key)) return INDEX_BY_NAME.get(key);
  // Fallback: tentativa de contains
  for (const c of COUNTRIES) {
    const desc = normalize(c.descricao);
    if (desc.includes(key) || key.includes(desc)) return c.codigo;
  }
  return undefined;
}

export function getCountryLabel(code: number): string | undefined {
  return COUNTRIES.find((c) => c.codigo === code)?.descricao;
}

export function getCountryOptions(): { label: string; value: number }[] {
  return COUNTRIES.map((c) => ({ label: c.descricao, value: c.codigo }));
}
